# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: location.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'location.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\"\x82\x01\n\x12LocationResMessage\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x11\n\tlongitude\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\t\x12\x0e\n\x06meters\x18\x04 \x01(\x05\x12\x12\n\nstart_date\x18\x05 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x06 \x01(\t\"M\n\x12LocationReqMessage\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\"=\n\x13LocationMessageList\x12&\n\tlocations\x18\x01 \x03(\x0b\x32\x13.LocationResMessage2C\n\x0fLocationService\x12\x30\n\x03Get\x12\x13.LocationReqMessage\x1a\x14.LocationMessageListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCATIONRESMESSAGE']._serialized_start=19
  _globals['_LOCATIONRESMESSAGE']._serialized_end=149
  _globals['_LOCATIONREQMESSAGE']._serialized_start=151
  _globals['_LOCATIONREQMESSAGE']._serialized_end=228
  _globals['_LOCATIONMESSAGELIST']._serialized_start=230
  _globals['_LOCATIONMESSAGELIST']._serialized_end=291
  _globals['_LOCATIONSERVICE']._serialized_start=293
  _globals['_LOCATIONSERVICE']._serialized_end=360
# @@protoc_insertion_point(module_scope)
