apiVersion: v1
kind: Service
metadata:
  labels:
    service: microservice-connection-api
  name: microservice-connection-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30011    
  - name: "5005"
    port: 5005
    targetPort: 5005
  selector:
    service: microservice-connection-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: microservice-connection-api
  name: microservice-connection-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: microservice-connection-api
  template:
    metadata:
      labels:
        service: microservice-connection-api
    spec:
      containers:
      - image: leon494/connection_api:v1.0.11
        name: microservice-connection-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
