apiVersion: v1
kind: Service
metadata:
  labels:
    service: microservice-app
  name: microservice-app
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
    nodePort: 30010
  selector:
    service: microservice-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: microservice-app
  name: microservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: microservice-app
  template:
    metadata:
      labels:
        service: microservice-app
    spec:
      containers:
      - image: leon494/microservice_app:v1.0.0
        name: microservice-app
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
      restartPolicy: Always
